version: "3"
services:
  db:
    image: postgres:13.8-alpine3.16
    restart: always
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
  api:
    build:
      context: ./api
    ports:
      - "5000:5001"
    environment:
      - API_PORT=5001
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    command: npm run start
    depends_on:
      - db
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    depends_on:
      - api
volumes:
  db-volume: