# New version
services:
  # A Docker web service
  - type: web
    name: api
    env: docker
    rootDir: api
    buildCommand: npm start
    envVars:
      - key: API_PORT
        value: 80
      - key: DATABASE_URL
        fromDatabase:
          name: todo-app
          property: connectionString
    plan: free
  - type: web
    name: client
    env: docker
    rootDir: client
    buildCommand: npm run build
    # staticPublishPath: ./build
    pullRequestPreviewsEnabled: true # optional
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: api
          envVarKey: RENDER_EXTERNAL_URL
    plan: free

databases:
  - name: todo-app
    plan: free
